export const ADD_PRODUCT_TO_BACKET = 'ADD_PRODUCT_TO_BASKET';
export const GET_NUMBERS_IN_BASKET = 'GET_NUMBERS_IN_BASKET';
export const ADD_PRODUCT_TO_WATCHLIST = 'ADD_PRODUCT_TO_WATCHLIST';
export const GET_NUMBERS_TO_WATCHLIST = 'GET_NUMBERS_TO_WATCHLIST';
export const CLEAR_PRODUCT = 'CLEAR_PRODUCT';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const INCREASE_QUANITY = 'INCREASE_QUANITY';