export const ADD_PRODUCT_TO_BACKET = 'ADD_PRODUCT_TO_BASKET';
export const GET_NUMBERS_IN_BASKET = 'GET_NUMBERS_IN_BASKET';
export const ADD_PRODUCT_TO_WATCHLIST = 'ADD_PRODUCT_TO_WATCHLIST';
export const GET_NUMBERS_TO_WATCHLIST = 'GET_NUMBERS_TO_WATCHLIST';
export const CLEAR_PRODUCT = 'CLEAR_PRODUCT';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const INCREASE_QUANITY = 'INCREASE_QUANITY';
export const DECREASE_QUANITY = 'DECREASE_QUANITY';
export const CLEAT_ALL_DETAILS = 'CLEAT_ALL_DETAILS';
export const REMOVE_PRODUCT_FROM_WATCHLIST = 'REMOVE_PRODUCT_FROM_WATCHLIST';
export const PLACE_ORDER_DIR = 'PLACE_ORDER_DIR';


